import type { Metadata } from "next";
import "./globals.css";
import MobileMenuProvider from "@/providers/MobileMenuProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <MobileMenuProvider>
      <html lang="en">
        <body>
          {children}
        </body>
      </html>
    </MobileMenuProvider>
  );
}
